create table person(
    id int generated by default as identity primary key,
    name varchar (100) not null unique,
    yearOfBirth int check ( yearOfBirth > 1900 ) not null
);

drop table book;

create table book(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    author varchar(100) not null,
    year int not null,
    person_id int references person(id) on delete set null
);

insert into person(name, yearOfBirth) values ('alex', 2000);
insert into person(name, yearOfBirth) values ('vova', 2010);
insert into person(name, yearOfBirth) values ('igor', 2020);
insert into person(name, yearOfBirth) values ('christof', 2011);

insert into book(name, author, year, person_id) values (
    'Над пропастью во ржи', 'Джером селинджер', 1951, null );
insert into book(name, author, year, person_id) values (
'День опричника', 'Владимир Сороки', 2006, null );
insert into book(name, author, year, person_id) values (
'Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018, null );
insert into book(name, author, year, person_id) values (
'Философия Java', 'Брюс Эккель', 2018, null );
insert into book(name, author, year, person_id) values (
'Психопатология обыденной жизни', 'Фрейд Зигмунд', 1904, null );
insert into book(name, author, year, person_id) values (
'Игра в бисер', 'Герман Гессе', 1943, null );
insert into book(name, author, year, person_id) values (
'Бытие и время', 'Мартин Хайдеггер', 1927, null );