create table person(
    id int generated by default as identity primary key,
    name varchar (100) not null unique,
    yearOfBirth int check ( yearOfBirth > 1900 ) not null
);

create table book(
                     id int generated by default as identity primary key,
                     name varchar(100) not null,
                     author varchar(100) not null,
                     year int not null,
                     person_id int references person(id) on delete set null,
                     assign_time timestamp
);

